version: "3"
services:
  app:
    image: elyspio/docker-update:arm64
    ports:
      - "4001:4001"
    environment:
      LOG_FOLDER: /var/logs
      SSH_REMOTE_USER: "ubuntu"
      DOCKER_SOCKET_PATH: "/var/run/host.sock"
    volumes:
      - /apps/docker-update/logs:/var/logs
      - /var/run/docker.sock:/var/run/host.sock
    container_name: "docker-updater"
